#!/bin/bash

jupyter labextension install @jupyterlab/fasta-extension @jupyterlab/geojson-extension @jupyterlab/katex-extension @jupyterlab/mathjax3-extension @jupyterlab/plotly-extension @jupyterlab/vega2-extension @jupyterlab/vega3-extension @jupyterlab/vega4-extension
