#!/bin/bash

jupyter labextension install @jupyterlab/fasta-extension @jupyterlab/geojson-extension @jupyterlab/json-extension @jupyterlab/katex-extension @jupyterlab/plotly-extension @jupyterlab/vdom-extension
