# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.0.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: jupyter@googlegroups.com
author_name: Project Jupyter
data_format: string
file_extension: ''
has_binder: false
has_settings: false
kind: frontend
labextension_name: '@jupyterlab/vega3-extension'
mimetype: ''
mimetype_name: ''
project_short_description: JupyterLab - Vega 3 and Vega-Lite 2 Mime Renderer Extension
python_name: jupyterlab_vega3
repository: https://github.com/jupyterlab/jupyter-renderers.git
test: true
viewer_name: ''

