# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.0.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: jupyter@googlegroups.com
author_name: Project Jupyter
data_format: string
file_extension: ''
has_binder: false
has_settings: true
kind: frontend
labextension_name: '@jupyterlab/katex-extension'
mimetype: ''
mimetype_name: ''
project_short_description: KaTeX math renderer for JupyterLab
python_name: jupyterlab_katex
repository: https://github.com/jupyterlab/jupyter-renderers.git
test: true
viewer_name: ''

