# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.0.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: jupyter@googlegroups.com
author_name: Project Jupyter
data_format: string
file_extension: ''
has_binder: false
has_settings: false
kind: frontend
labextension_name: '@jupyterlab/mathjax2-extension'
mimetype: ''
mimetype_name: ''
project_short_description: A MathJax Typesetting provider for JupyterLab 4 and above
python_name: jupyterlab_mathjax2
repository: https://github.com/jupyterlab/jupyter-renderers.git.git
test: true
viewer_name: ''

