name: Lint

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Base Setup
      uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

    - name: Install dependencies
      run: |
        python -m pip install -U jupyterlab~=3.2

    - name: Lint
      run: |
        jlpm
        jlpm run eslint:check
        jlpm run prettier:check